name: Node.js CI
on:
    push:
      branches: [main]
    pull_request:
      branches: [main] 

jobs:
    build:
      runs-on: self-hosted
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: '18'
  
        - name: Set Node.js memory allocation
          run: echo "::set-env name=NODE_OPTIONS::--max_old_space_size=4096"
  
        - name: Install Dependencies
          run: npm ci
  
        - name: Build Frontend
          run: |
            cd frontend
            npm ci
            npm run build
  