name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}   
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: |
          npm i
          cd frontend
          npm i
          npm run build
          cd ..
          pm2 stop 0
          pm2 start 0
          pm2 save 
          sudo service nginx

  